### ISSUE TITLE
Please add a working example.

### ISSUE THREAD

**Issue by cotestatnt** [onelife/Arduino_wolfssl#1]
...or at least more info about the use of library in an Arduino sketch.

**Comment by onelife** [comment]
Hi @cotestatnt,
[There](https://github.com/onelife/RTT-Crypto/tree/main/examples) are some example sketches.

**Comment by cotestatnt** [comment]
Great! I will try soon.
Thank you.

**Comment by zekageri** [comment]
Hi! 
I'm using an esp32 with Arduino framework. 
On Espressif's site there is a section on how to use wolfss for esp-IDF. Can it work with this Arduino port?
It says that the user does not have to do anything with the existing function names provided by espressif's TLS.
Can i use this lib for handling incoming and outgoing https requests without modifying mbedtls?

Here is the link and an image to [doc.espressif.com](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/protocols/esp_tls.html)

![image](https://user-images.githubusercontent.com/37899881/147943202-2a59f9fb-3985-4419-b6dd-d4e53ce8096e.png)

Meanwhile i will look up your examples and try to figure out myself. Thank you!

**Comment by onelife** [comment]
Hi @zekageri,
The library has not tested with esp32 platform yet. I will find a chance to test when got a board.

**Comment by zekageri** [comment]
Thank you so much. Iam really looking forward to it.

**Comment by gojimmypi** [comment]
Heads up we now have an Official wolfSSL Arduino library located here:

https://github.com/wolfSSL/Arduino-wolfSSL

This has been added to the Arduino Registry with https://github.com/arduino/library-registry/pull/4056.

This initial release has been tested with the ESP32 and the Arduino Due. In the very near future I'll have a PR for fine tuning a wider range of Arduino board support.

Please feel free to [open an issue](https://github.com/wolfSSL/wolfssl/issues/new/choose) for any boards needing attention.
