### ISSUE TITLE
INSTALL file?

### ISSUE THREAD

**Issue by BertHav** [onelife/Arduino_wolfssl#2]
the README.MD points to "See INSTALL file for build instructions." But where can I find this file?

Regards Bert.

**Comment by onelife** [comment]
Hi @BertHav, the file is available in the upstream [repo](https://github.com/wolfSSL/wolfssl).

**Comment by gojimmypi** [comment]
We now have an Official wolfSSL Arduino library located here:

https://github.com/wolfSSL/Arduino-wolfSSL

This has been added to the Arduino Registry with https://github.com/arduino/library-registry/pull/4056.

This initial release has been tested with the ESP32 and the Arduino Due. In the very near future I'll have a PR for fine tuning a wider range of Arduino board support.

Please feel free to [open an issue](https://github.com/wolfSSL/wolfssl/issues/new/choose) for any boards needing attention.
