### ISSUE TITLE
Setting up an official wolfSSL library

### ISSUE THREAD

**Issue by gojimmypi** [onelife/Arduino_wolfssl#3]
Greetings @onelife and thank you for your efforts to install wolfSSL where it was otherwise missing.

I'm in the process of setting up an official wolfSSL library for Arduino.

Can we collaborate on a smooth transition and take down your current library once ours is in place?

Thank you

Jim (at) wolfSSL.com
wolfSSL Software Engineer

**Comment by onelife** [comment]
Hi @gojimmypi,

Sure thing.

**Comment by gojimmypi** [comment]
Thank you for your cooperation @onelife !

We now have an Official wolfSSL Arduino library located here:

https://github.com/wolfSSL/Arduino-wolfSSL

This has been added to the Arduino Registry with https://github.com/arduino/library-registry/pull/4056.

This initial release has been tested with the ESP32 and the Arduino Due. In the very near future I'll have a PR for fine tuning a wider range of Arduino board support.

Please feel free to [open an issue](https://github.com/wolfSSL/wolfssl/issues/new/choose) for any boards needing attention.
