### ISSUE TITLE
[FR] Project Examples for PlatformIO Registry

### ISSUE THREAD

**Issue by LuckyToaster** [onelife/Arduino_wolfssl#4]
Hi,

Currently, the [library page](https://registry.platformio.org/libraries/onelife/wolfssl) in the PlatformIO Registry doesn't contain any quick start projects for developers. Such examples serve both to highlight widespread use cases and to help newcomers to get up and running much more quickly.

Please consider adding a few comprehensive project examples to the PlatformIO Registry.

Useful links:
- https://registry.platformio.org/libraries/onelife/wolfssl
- https://docs.platformio.org/en/latest/manifests/library-json/fields/examples.html

**Comment by gojimmypi** [comment]
Please see https://github.com/platformio/platformio-registry/issues/85. I'll be adding Official PlatformIO support for wolfSSL in the near future.

We now have an Official wolfSSL Arduino library located here:

https://github.com/wolfSSL/Arduino-wolfSSL

This has been added to the Arduino Registry with https://github.com/arduino/library-registry/pull/4056.

This initial release has been tested with the ESP32 and the Arduino Due. In the very near future I'll have a PR for fine tuning a wider range of Arduino board support.

Please feel free to [open an issue](https://github.com/wolfSSL/wolfssl/issues/new/choose) for any boards needing attention.
